### ISSUE TITLE
Switch to iso date format

### ISSUE THREAD

**Issue by tebowy** [kvdveer/timeghost#1]
Could you  consider that? I am so sorry, but I find all other date formats unwieldy in programming context, as well as data entry (which this project is the most IMHO).

In the meantime, I'm making a small PR with some dates.

**Comment by kvdveer** [comment]
The format you're probably referring to is `YYYY-MM-DD`, which is supported. This format doesn't deal with BC dates properly, so I'm not able to use that exclusively. 

For easy copy-pasting, I chose to use a fuzzy date format. A reasonable subset of ISO8601 is supported, although madness like `P1Y2M10DT2H30M/2008-05-11T15:30:00Z` is not.

Closing this now, as I think a reasonable compromise is already in place.
